- name: Copy Create Cluster Script File
  template:
    src: create_cluster.j2
    dest: /tmp/create_cluster.sh
    mode: '0755'
  delegate_to: "{{ groups['redis'][0] }}"
  run_once: true
- name: Install expect tool
  yum:
    name: expect
    state: latest
  delegate_to: "{{ groups['redis'][0] }}"
  run_once: true
- name: EXEC Create Cluster Script
  shell: /tmp/create_cluster.sh
  delegate_to: "{{ groups['redis'][0] }}"
  run_once: true
 # ignore_errors: yes
