- name: Create mastaer Dir
  file: 
    path: "/data/redis-{{ redis_master_port }}/bin"
    state: directory
    mode: '0755'


- name: Copy redis files 
  copy: 
    src: "{{ item }}"
    dest: "/data/redis-{{ redis_master_port }}/bin"
  with_fileglob:
    - "../files/*"

- name: Copy redis configuration file
  templates:
    src: redis.conf.j2
    dest: "/data/redis-{{ redis_master_port }}/redis.conf"
  notify: Restart Redis Server
- name: Start redis server


- name: Create redis-cluster-master





- name: Cheack port 
  wait_for: 
    port: "{{ redis_master_port }}"
    state: started
      
